name: Publish VS Code Extension

# Allow manual triggers
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type: minor or major (default: patch)"
        required: false
        default: "patch" # Default to patch if not provided
        
permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Install vsce CLI globally
    - name: Install vsce CLI
      run: npm install -g @vscode/vsce

    # Step 5: Verify the VSCE_TOKEN 
    - name: Test the VSCE_TOKEN 
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      run: |
        vsce verify-pat -p ${VSCE_PAT}
        echo ${{ github.event.inputs.release_type }}

    # Step 6: Publish and get new version number
    - name: Publish to VS Code Marketplace
      id: publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      run: |
        echo "new_version=${{ github.run_id }}" >> $GITHUB_ENV
    #    NEW_VERSION=$(vsce publish ${{ github.event.inputs.release_type }} -p ${VSCE_PAT} | grep -Eo "([0-9]+\.[0-9]+\.[0-9]+)")
    #    echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
    
    # Step 7: Create a new branch  # TODO: remove the ehcho "new_version... line.
    - name: Create a new branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="version-bump-${new_version}"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b $BRANCH_NAME
        echo "Branch created: $BRANCH_NAME" > test.txt
        git add test.txt
        git commit -m "Version bump to ${new_version}"
        git push --set-upstream origin $BRANCH_NAME
        gh pr create --title "Version bump to ${new_version}" --body "Testing PR for version bump to ${new_version}" --base test-actions --head $BRANCH_NAME
        
